### ISSUE TITLE
Updates to dart-markdown

### ISSUE THREAD

**Issue by Simn** [dpeek/haxe-markdown#16]
Hey David,

there have been quite a few commits to dart-markdown and I was wondering if there is anything we should port back to haxe-markdown. I was looking through the commits but it's hard for me to tell what is specific to dart or the library structure and what are actual improvements to markdown parsing.

**Comment by dpeek** [comment]
Most of it seems like house keeping – CI, tests and some cleanup – although possibly a fix or two we could benefit from. I'm working on supporting the commonmark test suite, which has taken the code base in a quite different direction. Once that suite is passing hopefully all our edge cases will be covered anyway. Better to fix individual issues on this version for now.
