### ISSUE TITLE
Anchor link discrepancy

### ISSUE THREAD

**Issue by Simn** [dpeek/haxe-markdown#18]
Compare the anchor links between these two pages:

http://haxe.org/manual/cr-resources.html
https://github.com/HaxeFoundation/HaxeManual/blob/master/md/manual/cr-resources.md

The github version links to this:
cr-resources.md#841-embedding-resources

On haxe.org we have this instead:
cr-resources.html#8.4.1-embedding-resources

So it looks like the dots are removed in github's markdown interpretation.

I don't know which one should be considered "correct". Or is this not related to haxe-markdown at all?

**Comment by dpeek** [comment]
This isn't really a markdown thing, I'm guessing that @jasononeil is traversing the parsed AST and generating those anchors.

Aaand I'm back:
https://github.com/HaxeFoundation/haxe.org/blob/b838a82d278cb1887523c0e53f7173b67e2805bb/src/app/api/ManualUpdateApi.hx#L138

**Comment by Simn** [comment]
Thanks for confirming, I kind of figured this would be the wrong place to complain right after opening the issue.
