### ISSUE TITLE
Need Tables support

### ISSUE THREAD

**Issue by fzzr-** [dpeek/haxe-markdown#22]
Related issue: https://github.com/HaxeFoundation/haxelib/issues/254

**Comment by jasononeil** [comment]
Tables  do work.  For example this renders correctly:

```md
| assert            | done   |                          |
| Buffer            | done   |                          |
| child_processes   | done   |                          |
| cluster           | done   |                          |
```

The README that doesn't render correctly uses a header like this, and fails to render:

```md
| module            | status | comment                  |
|-------------------|--------|--------------------------|
| assert            | done   |                          |
| Buffer            | done   |                          |
| child_processes   | done   |                          |
| cluster           | done   |                          |
```

In fact, haxe-markdown does support headers, but unlike Github, it needs some extra spacing:

```md
| module            | status | comment                  |
| ------------------- | -------- | -------------------------- |
| assert            | done   |                          |
| Buffer            | done   |                          |
| child_processes   | done   |                          |
```

Notice the spaces between the pipes (`|`) and the hyphens (`-----`).  So the only glitch here is that the table syntax needs to be a bit more flexible. 

If you want to take a go at fixing it the problem will be in here somewhere: https://github.com/dpeek/haxe-markdown/blob/master/src/markdown/BlockParser.hx#L739-L821
